CREATE TABLE PRODUCTOS(
    PRODUCTO_ID SERIAL NOT NULL,
    PRODUCTO_NOMBRE VARCHAR(200),
    PRODUCTO_PRECIO DECIMAL(10, 2),
    PRODUCTO_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (PRODUCTO_ID)
);

CREATE TABLE VENTAS (
    VENTA_ID SERIAL NOT NULL,
    VENTA_FECHA DATETIME YEAR TO MINUTE,
    VENTA_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (VENTA_ID)
);

CREATE TABLE DETALLE_VENTAS (
    DETALLE_ID SERIAL NOT NULL,
    DETALLE_VENTA INTEGER,
    DETALLE_PRODUCTO INTEGER,
    DETALLE_CANTIDAD INTEGER,
    DETALLE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (DETALLE_ID),
    FOREIGN KEY (DETALLE_VENTA) REFERENCES VENTAS (VENTA_ID),
    FOREIGN KEY (DETALLE_PRODUCTO) REFERENCES PRODUCTOS (PRODUCTO_ID)
);


INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_PRECIO) VALUES ('MESA', 1500.25)
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_PRECIO) VALUES ('ESCRITORIO', 9000)
INSERT INTO PRODUCTOS (PRODUCTO_NOMBRE, PRODUCTO_PRECIO) VALUES ('COMPUTADORA', 15000)

INSERT INTO VENTAS (VENTA_FECHA) VALUES (CURRENT);
INSERT INTO VENTAS (VENTA_FECHA) VALUES (CURRENT);

INSERT INTO DETALLE_VENTAS (DETALLE_VENTA, DETALLE_PRODUCTO, DETALLE_CANTIDAD) VALUES (1,1,1);
INSERT INTO DETALLE_VENTAS (DETALLE_VENTA, DETALLE_PRODUCTO, DETALLE_CANTIDAD) VALUES (1,3,2);
INSERT INTO DETALLE_VENTAS (DETALLE_VENTA, DETALLE_PRODUCTO, DETALLE_CANTIDAD) VALUES (2,2,1);
INSERT INTO DETALLE_VENTAS (DETALLE_VENTA, DETALLE_PRODUCTO, DETALLE_CANTIDAD) VALUES (2,4,1);

SELECT PRODUCTO_NOMBRE AS PRODUCTO, SUM (DETALLE_CANTIDAD) AS CANTIDAD 
FROM DETALLE_VENTAS
INNER JOIN PRODUCTOS ON DETALLE_PRODUCTO = PRODUCTO_ID 
WHERE DETALLE_SITUACION = 1 
GROUP BY PRODUCTO_NOMBRE
